const customerDevelopment = [
  {
    "Act No": "Standards Organization of Nigeria Act",
    "Legislation Name ": "",
    "Act URL": "",
    Regulator: "",
    Section: "",
    "Compliance Name": "",
    "Compliance Description": "",
    "Task Frequency": "",
    Penalty: "",
    Criticality: "",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Cap. 59 LFN 2004",
    "Legislation Name ": "Standards Organization of Nigeria Act",
    "Act URL": "https://lawsofnigeria.placng.org/laws/S9.pdf",
    Regulator: "Standard Council of Nigeria",
    Section: "Section 16",
    "Compliance Name": "Duty to compliance with established standards",
    "Compliance Description":
      "The Company is  expected to comply with the manufacture industrial standard that will from time to time be set by the Minister. ",
    "Task Frequency": "At all times",
    Penalty: "Conviction with fine and or imprisonment or both.",
    Criticality: "High",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Trade Mark Act",
    "Legislation Name ": "",
    "Act URL": "",
    Regulator: "",
    Section: "",
    "Compliance Name": "",
    "Compliance Description": "",
    "Task Frequency": "",
    Penalty: "",
    Criticality: "",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Cap T13 LFN 2004",
    "Legislation Name ": "Trade Mark Act",
    "Act URL": "https://nigeria.tradeportal.org/media/Trade%20Mark%20Act.pdf",
    Regulator: "Nigerian Trademarks Registry",
    Section: "Section 11",
    "Compliance Name": "Duty not to register deceptive, confusing and scandalous trade marks.",
    "Compliance Description": " Deceptive or scandalous marks are not registrable",
    "Task Frequency": "Atll all times",
    Penalty: "Not stated",
    Criticality: "Low",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No":
      "Counterfeit and Fake Drugs and Unwholesome Processed Foods (Miscellaneous Provisions) Act",
    "Legislation Name ": "",
    "Act URL": "",
    Regulator: "",
    Section: "",
    "Compliance Name": "",
    "Compliance Description": "",
    "Task Frequency": "",
    Penalty: "",
    Criticality: "",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Cap. C34 LFN 2004",
    "Legislation Name ":
      "Counterfeit and Fake Drugs and Unwholesome Processed Foods (Miscellaneous Provisions) Act",
    "Act URL":
      "https://www.nafdac.gov.ng/wp-content/uploads/Files/Resources/Regulations/NAFDAC_Acts/COUNTERFEIT-AND-FAKE-DRUGS-AND-UNWHOLESOME-PROCESSED-FOODS-Cap.-C.34.pdf",
    Regulator: "Federal Task Force",
    Section: "Section 1",
    "Compliance Name":
      "Duty not to sell counterfeit and fake drugs and unwholesome processed foods",
    "Compliance Description":
      "The Company shall not  produce, import, manufacture, sell, distribute or be in possession of; or sell or display for the purpose of sale; or aid or abet any person to produce, import, manufacture, sell, distribute or display for the purpose of sale, any counterfeit, adulterated, banned or fake, substandard or expired drug or unwholesome processed food, in any form whatsoever.",
    "Task Frequency": "At all times",
    Penalty: "Conviction with fine and or imprisonment for company and officers/directors",
    Criticality: "High",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Federal Competition and Consumer Protection Act (FCCPA) 2018",
    "Legislation Name ": "",
    "Act URL": "",
    Regulator: "",
    Section: "",
    "Compliance Name": "",
    "Compliance Description": "",
    "Task Frequency": "",
    Penalty: "",
    Criticality: "",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "2018",
    "Legislation Name ": "Federal Competition and Consumer Protection Act (FCCPA)",
    "Act URL": "https://www.fccpc.gov.ng/uploads/FCCPA.pdf",
    Regulator: "Federal Competiton and Consumer Protection Commission",
    Section: "Section 114",
    "Compliance Name": "Duty to publis information in plain and understandable language",
    "Compliance Description":
      "Producer should produce information in plain and understandable language.",
    "Task Frequency": "At all times",
    Penalty: "Conviction with fine for company and officers/directors",
    Criticality: "High",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "2018",
    "Legislation Name ": "Federal Competition and Consumer Protection Act (FCCPA)",
    "Act URL": "https://www.fccpc.gov.ng/uploads/FCCPA.pdf",
    Regulator: "Federal Competiton and Consumer Protection Commission",
    Section: "Section 115",
    "Compliance Name": "Duty to disclose  of price of goods and services.",
    "Compliance Description":
      "The Company shall not display any goods or services for sale without adequately displaying to the consumer a price of those goods or services.",
    "Task Frequency": "At all times",
    Penalty: "Conviction with fine for company and officers/directors",
    Criticality: "High",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "2018",
    "Legislation Name ": "Federal Competition and Consumer Protection Act (FCCPA)",
    "Act URL": "https://www.fccpc.gov.ng/uploads/FCCPA.pdf",
    Regulator: "Federal Competiton and Consumer Protection Commission",
    Section: "Section 116 (3)",
    "Compliance Name": "Duty not to sell goods with misleading or altered trade descriptions.",
    "Compliance Description":
      " The company shall not sell to customers goods with misleading or altered trade descriptions",
    "Task Frequency": "At all times",
    Penalty: "Conviction with fine for company and officers/directors",
    Criticality: "High",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "2018",
    "Legislation Name ": "Federal Competition and Consumer Protection Act (FCCPA)",
    "Act URL": "https://www.fccpc.gov.ng/uploads/FCCPA.pdf",
    Regulator: "Federal Competiton and Consumer Protection Commission",
    Section: "Section 117",
    "Compliance Name":
      "Duty to disclose when goods have been  reconditioned or are second-hand goods.",
    "Compliance Description":
      " The Company must inform customers if the goods for sale have been recnditioned or are second hand goods",
    "Task Frequency": "At all times",
    Penalty: "Conviction with fine for company and officers/directors",
    Criticality: "High",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "2018",
    "Legislation Name ": "Federal Competition and Consumer Protection Act (FCCPA)",
    "Act URL": "https://www.fccpc.gov.ng/uploads/FCCPA.pdf",
    Regulator: "Federal Competiton and Consumer Protection Commission",
    Section: "Section 123(1)",
    "Compliance Name": "Duty not to misrepresent facts to consumers when marketing goods.",
    "Compliance Description":
      "The Company shall not to make any representation that is likely to imply false or incorrect representation concerning goods and services  ",
    "Task Frequency": "At all times",
    Penalty: "Conviction with fine for company and officers/directors",
    Criticality: "High",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "2018",
    "Legislation Name ": "Federal Competition and Consumer Protection Act (FCCPA)",
    "Act URL": "https://www.fccpc.gov.ng/uploads/FCCPA.pdf",
    Regulator: "Federal Competiton and Consumer Protection Commission",
    Section: "Section 127(1)",
    "Compliance Name": "Duty not sell goods at unfair, unreasonable, or unjust contract terms.",
    "Compliance Description":
      "The company shall not offer to supply, supply or enter into an agreement to supply any goods or services at a price that is manifestly unfair, unreasonable or unjust or on terms that are unfair, unreasonable or unjust.",
    "Task Frequency": "At all times",
    Penalty: "Conviction with fine for company and officers/directors",
    Criticality: "High",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "2018",
    "Legislation Name ": "Federal Competition and Consumer Protection Act (FCCPA)",
    "Act URL": "https://www.fccpc.gov.ng/uploads/FCCPA.pdf",
    Regulator: "Federal Competiton and Consumer Protection Commission",
    Section: "Section 134",
    "Compliance Name": "Duty to label goods properly",
    "Compliance Description":
      "The Company shall label or describe the goods in a manner that will be easily traceable to the manufacturer, importer, or distributor",
    "Task Frequency": "At all times",
    Penalty: "Conviction with fine for company and officers/directors",
    Criticality: "High",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "2018",
    "Legislation Name ": "Federal Competition and Consumer Protection Act (FCCPA)",
    "Act URL": "https://www.fccpc.gov.ng/uploads/FCCPA.pdf",
    Regulator: "Federal Competiton and Consumer Protection Commission",
    Section: "Section 135",
    "Compliance Name": "Duty to withdraw hazardous goods from the market.",
    "Compliance Description":
      "Upon becoming aware of any unforeseen hazard arising from the use of goods already placed on the market, the company  such goods shall notify the general public immediately of such risk or danger and cause such goods to be withdrawn from the market",
    "Task Frequency": "Upon becoming aware",
    Penalty: "Conviction with fine for company and officers/directors",
    Criticality: "High",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "NAFDAC Cosmetic Products (Prohibition of bleaching agents, etc) Regulations ",
    "Legislation Name ": "",
    "Act URL": "",
    Regulator: "",
    Section: "",
    "Compliance Name": "",
    "Compliance Description": "",
    "Task Frequency": "",
    Penalty: "",
    Criticality: "",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Cap. N1 LFN 2004",
    "Legislation Name ":
      "NAFDAC Cosmetic Products (Prohibition of bleaching agents, etc) Regulations ",
    "Act URL":
      "https://www.nafdac.gov.ng/wp-content/uploads/Files/Resources/Regulations/NAFDAC_Acts/NAFDAC-ACT-Cap-N.-1-LFN-2004.pdf",
    Regulator: "NAFDAC",
    Section: "Regulation 1",
    "Compliance Name": "Duty not to sell adulterated cosmetic products",
    "Compliance Description":
      "The Company shall not engage in the sale of adulterated, injurious or cosmetic  products with bleaching agents.",
    "Task Frequency": "At all times",
    Penalty: "Conviction with fine and or imprisonment",
    Criticality: "High",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
];

const corpoateAffairs = [
  {
    "Act No": "Cybercrimes (Prohibition and Prevention) Act, 2015",
    "Legislation Name ": "",
    "Act URL": "",
    Regulator: "",
    Section: "",
    "Compliance Name": "",
    "Compliance Description": "",
    "Task Frequency": "",
    Penalty: "",
    Criticality: "",
    "Significant Judicial Intervention": "",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2015,
    "Legislation Name ": " Cybercrimes (Prohibition, Prevention, Etc) Act, 2015 ",
    "Act URL":
      "https://www.cert.gov.ng/ngcert/resources/CyberCrime__Prohibition_Prevention_etc__Act__2015.pdf",
    Regulator: "Office of the National Security Adviser (NSA)",
    Section: "Section 17 (1) (a)",
    "Compliance Name": "Electronic signature",
    "Compliance Description":
      "Do not with the intent to defraud and or misrepresent, forge through electronic devices another person or company’s signature ",
    "Task Frequency": "All the time",
    Penalty: "Conviction with fine and/ or imprisonment.",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2015,
    "Legislation Name ": " Cybercrimes (Prohibition, Prevention, Etc) Act, 2015 ",
    "Act URL":
      "https://www.cert.gov.ng/ngcert/resources/CyberCrime__Prohibition_Prevention_etc__Act__2015.pdf",
    Regulator: "Office of the National Security Adviser (NSA)",
    Section: "Section 21 (1) and (3) ",
    "Compliance Name": "Reporting of Cyber Threats",
    "Compliance Description":
      "Inform the National Computer Emergency Response Team (CERT) Coordination Center of any attacks, intrusions and other disruptions liable to hinder the functioning of another computer system or network.",
    "Task Frequency": "Within 7 days of occurrence ",
    Penalty: "Fine and denial of internet services",
    Criticality: "Medium",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2015,
    "Legislation Name ": " Cybercrimes (Prohibition, Prevention, Etc) Act, 2015 ",
    "Act URL":
      "https://www.cert.gov.ng/ngcert/resources/CyberCrime__Prohibition_Prevention_etc__Act__2015.pdf",
    Regulator: "Office of the National Security Adviser (NSA)",
    Section: "Section 25 (1)",
    "Compliance Name": "Cybersquatting ",
    "Compliance Description":
      "Do not intentionally take or make use of any brand identity or trademark belonging to an individual, company or the government, on the internet or any other computer network, without authority or right, for the purpose of interfering with their use.",
    "Task Frequency": "All the time",
    Penalty: "Conviction with fine and/ or imprisonment.",
    Criticality: "Medium",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Federal Competition and Consumer Protection Act 2018",
    "Legislation Name ": "",
    "Act URL": "",
    Regulator: "",
    Section: "",
    "Compliance Name": "",
    "Compliance Description": "",
    "Task Frequency": "",
    Penalty: "",
    Criticality: "",
    "Significant Judicial Intervention": "",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 28(5) & 31",
    "Compliance Name": "Duty to provide reasonable facility to authorised officer  ",
    "Compliance Description":
      "Provide reasonable facilities and assistance to an authorised officer in executing a warrant issued under the Act",
    "Task Frequency": "All the time",
    Penalty: "Fine or imprisonment",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 33 (3)",
    "Compliance Name": "Summons to attend and give evidence or produce documents",
    "Compliance Description":
      "Appear before the commission in compliance with a summons or produce required documents",
    "Task Frequency": "All the time",
    Penalty: "Fine or imprisonment",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 36",
    "Compliance Name": "Duty to preserve records",
    "Compliance Description":
      "Do not destroy records with the intent to mislead the commission or impede any investigation or inquiry",
    "Task Frequency": "All the time",
    Penalty: "Fine or imprisonment",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 59",
    "Compliance Name": "Restrictive agreements",
    "Compliance Description":
      "Do not draft agreements that seeks to prevent, restrict or distort competition in any market, except authorised by the commission",
    "Task Frequency": "All the time",
    Penalty: "On conviction, fine or 10% of it turnover and corporate liability",
    Criticality: "Low",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 61 - 63",
    "Compliance Name": "Avoid collision arrangements/agreements ",
    "Compliance Description":
      "Do not enter any collision arrangement with any undertaking that seeks to distort demand and supply or free market compeition",
    "Task Frequency": "All the time",
    Penalty: "On conviction, fine or 10% of it turnover and corporate liability",
    Criticality: "Low",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 65",
    "Compliance Name": "Prohibition of minimum resale price maintenance.",
    "Compliance Description":
      "Do not enter into any agreement that seeks to withhold supplies of any goods or services from a dealer seeking to obtain them for resale on the ground that the dealer has sold goods or services at a price below the resale price or has supplied them to a third party who had done so.",
    "Task Frequency": "All the time",
    Penalty: "On conviction, fine or 10% of it turnover and corporate liability",
    Criticality: "Low",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 78(b) & 80",
    "Compliance Name": "Duty to furnish information ",
    "Compliance Description":
      "When the commission is conducting any monopoly investigation, the company  is expected to furnish the commission with such information as the commission may consider necessary for the purpose of conducting such investigation.",
    "Task Frequency": "Upon receiving notice in writing from the commission",
    Penalty: "Fine",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 95(3)",
    "Compliance Name": " Small merger notification",
    "Compliance Description":
      "The commission may require the parties to a small merger to notify it of the merger if the merger substantially prevent or lessen competiton",
    "Task Frequency": "Within six month of the merger",
    Penalty: "Nil",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 96(1) (4)",
    "Compliance Name": "Notification of large merger ",
    "Compliance Description":
      "Notify the commission of a large merger and do not implement it unless it is approved by the commision   ",
    "Task Frequency": "All the time",
    Penalty: "Action taken void",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 108",
    "Compliance Name": "Conspiracy to restrain trade",
    "Compliance Description":
      "Do not conspire with another business to limit the faciulities for transporting, producing, manufacturing, storing, and dealing in goods and services",
    "Task Frequency": "All the time",
    Penalty: "Fine max. of 10% of turnover and corporate liability ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 110",
    "Compliance Name": "Obstruction of investigation of inquiry",
    "Compliance Description": "Do not obstruct investigation or inquiry by the Commission.",
    "Task Frequency": "All the time",
    Penalty: "Fine max. of 10% of turnover and corporate liability ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 112",
    "Compliance Name": "Giving of false or misleading information",
    "Compliance Description":
      "Do not give the Commission or an authorized officer of the commission false or misleading information.",
    "Task Frequency": "All the time",
    Penalty: "Fine max. of 10% of turnover and corporate liability ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 114(1)",
    "Compliance Name": "Right of Information in a plain language",
    "Compliance Description":
      " All information notice or document meant to be displayed to consumer must be done in a plain language.",
    "Task Frequency": "All the time",
    Penalty: "Nil",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 115(1)",
    "Compliance Name": "Section Disclosure of Price of goods or service",
    "Compliance Description":
      "Do not display any goods or services for sale without adequately displaying to the consumer a price of those goods or services.",
    "Task Frequency": "All the time",
    Penalty: "Nil",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 116",
    "Compliance Name": "A trade description of misleading goods",
    "Compliance Description":
      "Trade description or labelling is required for goods that are likely to mislead consumers as to any matter implied or expressed in that trade description",
    "Task Frequency": "All the time",
    Penalty: "Nil",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2020",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 118",
    "Compliance Name": " Duty to provide sales record to Consumer",
    "Compliance Description":
      "Provide a written record of each transaction to any consumer to whom goods or services are sold or rendered to unless where it is impracticable ",
    "Task Frequency": "All the time",
    Penalty: "Nil",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2020",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 123",
    "Compliance Name": "General standards for the marketing of goods and services.",
    "Compliance Description":
      "Do not to make any representation that is likely to imply false or incorrect representation concerning the company's goods and services  ",
    "Task Frequency": "All the time",
    Penalty: "Nil",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2021",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 125",
    "Compliance Name": "Consumer's rights",
    "Compliance Description":
      "Do not give false, misleading or deceptive representations concerning a material fact to a consumer or prospective consumer or fails to correct an apparent misrepresentation.",
    "Task Frequency": "All the time",
    Penalty: "Exposure to civil laibility",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2021",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 126",
    "Compliance Name": "Representation and publication testimonials",
    "Compliance Description":
      "Do not make representation to the public that a test as to performance, efficacy or length of life of the goods or service has been made by any person or publish a testimonial to that effect unless as a stated in the Act ",
    "Task Frequency": "All the time",
    Penalty: "Nil",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2022",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 127",
    "Compliance Name": "Duty not to make Unfair and unreasonable contract terms ",
    "Compliance Description":
      "Do not offer or enter into an agreement to supply any goods and services that is manifestly unfair and unreasonable or unjust",
    "Task Frequency": "All the time",
    Penalty: "Nil",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2023",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 128",
    "Compliance Name": "Notice required to be provided to consumer in certain condition",
    "Compliance Description":
      "Any notice to consumer or potential consumer which purport to limit, impose or constitute a risk or liability on the consumer or any person shall be drawn to the attention of the consumer in a conspicous manner ",
    "Task Frequency": "All the time",
    Penalty: "Nil",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2023",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 129",
    "Compliance Name": "Consumer's rights",
    "Compliance Description":
      "Do not make any transaction or agreement seeking to defeat the purposes and policy of this Act, mislead or deceive the consumer, or subject a consumer to fraudulent conduct.",
    "Task Frequency": "All the time",
    Penalty: "Nil",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2023",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 134",
    "Compliance Name": "Duty to label goods properly",
    "Compliance Description":
      "Label or describe goods in a manner that will be easily traceable to the company",
    "Task Frequency": "All the time",
    Penalty: "Fine max. of 10% of turnover and corporate liability ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2023",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 135",
    "Compliance Name": "Duty to withdraw hazardous goods from the market.",
    "Compliance Description":
      "Notify the general public immediately of any unforeseen hazard arising from the use of goods already placed on the market, and cause such goods to be withdrawn from the market.",
    "Task Frequency": "Upon becoming aware",
    Penalty: "Fine max. of 10% of turnover and corporate liability ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
];

const itComplaince = [
  {
    "Act No": "N/A",
    "Legislation Name ": "Nigeria Data Protection Regulation, 2019.",
    "Act URL": "https://ndpr.nitda.gov.ng/Content/Doc/NigeriaDataProtectionRegulation.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Reg. 2.1 (1)",
    "Compliance Name": "Process data on legitimate grounds and consent of data subject",
    "Compliance Description":
      "Collect and process personal data for lawful purpose and with the consent of the data subject.",
    "Task Frequency": "At all times",
    Penalty:
      "Processing over 10, 000 Data Subjescts: 2% of the Annual Gross Revenue of the preceding year or 10million Naira which ever is greater;  Less than 10,000 Data subjects: 1% of the Annual Gross Reveune of the preceding year or 2million naira, whichever is greater. ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "Nigeria Data Protection Regulation, 2019.",
    "Act URL": "https://ndpr.nitda.gov.ng/Content/Doc/NigeriaDataProtectionRegulation.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Reg. 2.3 (1)",
    "Compliance Name": "Procuring data with consent ",
    "Compliance Description":
      "Obtain personal data with consent, without fraud, coercion, or undue influence",
    "Task Frequency": "At all times",
    Penalty:
      "Processing over 10, 000 Data Subjescts: 2% of the Annual Gross Revenue of the preceding year or 10million Naira which ever is greater;  Less than 10,000 Data subjects: 1% of the Annual Gross Reveune of the preceding year or 2million naira, whichever is greater. ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "Nigeria Data Protection Regulation, 2019.",
    "Act URL": "https://ndpr.nitda.gov.ng/Content/Doc/NigeriaDataProtectionRegulation.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Reg. 2.3 (c)",
    "Compliance Name": "Duty to inform Data Subject of right to withdrawal ",
    "Compliance Description":
      " Inform data subject of their right to withdraw their personal data and include the method for withdrawal ",
    "Task Frequency": "Prior to giving consent",
    Penalty:
      "Processing over 10, 000 Data Subjescts: 2% of the Annual Gross Revenue of the preceding year or 10million Naira which ever is greater;  Less than 10,000 Data subjects: 1% of the Annual Gross Reveune of the preceding year or 2million naira, whichever is greater. ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "",
    "Legislation Name ": "Nigeria Data Protection Regulation, 2019.",
    "Act URL": "",
    Regulator: "",
    Section: "Reg 2.3 (e) ",
    "Compliance Name": "Consent to transfer data",
    "Compliance Description":
      " Inform data subject that their data will be transferred to a third party for any reason",
    "Task Frequency": "Anytime Data will be transffered ",
    Penalty:
      "Processing over 10, 000 Data Subjescts: 2% of the Annual Gross Revenue of the preceding year or 10million Naira which ever is greater;  Less than 10,000 Data subjects: 1% of the Annual Gross Reveune of the preceding year or 2million naira, whichever is greater. ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "Nigeria Data Protection Regulation, 2019.",
    "Act URL": "https://ndpr.nitda.gov.ng/Content/Doc/NigeriaDataProtectionRegulation.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Reg. 2.4 (b)",
    "Compliance Name": "Third party accountability",
    "Compliance Description":
      "The company is liable for the actions and inactions of third party who handles personal data of a data subject.",
    "Task Frequency": "At all times",
    Penalty:
      "Processing over 10, 000 Data Subjescts: 2% of the Annual Gross Revenue of the preceding year or 10million Naira which ever is greater;  Less than 10,000 Data subjects: 1% of the Annual Gross Reveune of the preceding year or 2million naira, whichever is greater. ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "Nigeria Data Protection Regulation, 2019.",
    "Act URL": "https://ndpr.nitda.gov.ng/Content/Doc/NigeriaDataProtectionRegulation.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Reg. 2.5",
    "Compliance Name": "Publicity and clarity of privacy policy",
    "Compliance Description":
      "Ensure that all personal data collection medium contains a simple and conspicous privacy policy ",
    "Task Frequency": "At all times",
    Penalty:
      "Processing over 10, 000 Data Subjescts: 2% of the Annual Gross Revenue of the preceding year or 10million Naira which ever is greater;  Less than 10,000 Data subjects: 1% of the Annual Gross Reveune of the preceding year or 2million naira, whichever is greater. ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "Nigeria Data Protection Regulation, 2019.",
    "Act URL": "https://ndpr.nitda.gov.ng/Content/Doc/NigeriaDataProtectionRegulation.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Reg. 2.6",
    "Compliance Name": "Maintaining data security",
    "Compliance Description":
      "Develop security measures to protect data e.g  firewalls, data encryption, etc",
    "Task Frequency": "At all times",
    Penalty:
      "Processing over 10, 000 Data Subjescts: 2% of the Annual Gross Revenue of the preceding year or 10million Naira which ever is greater;  Less than 10,000 Data subjects: 1% of the Annual Gross Reveune of the preceding year or 2million naira, whichever is greater. ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "Nigeria Data Protection Regulation, 2019.",
    "Act URL": "https://ndpr.nitda.gov.ng/Content/Doc/NigeriaDataProtectionRegulation.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Reg 2.7 ",
    "Compliance Name": "Data Processing contract",
    "Compliance Description":
      " The company must have a data processing contract when using a third party processor",
    "Task Frequency": "At all times",
    Penalty:
      "Processing over 10, 000 Data Subjescts: 2% of the Annual Gross Revenue of the preceding year or 10million Naira which ever is greater;  Less than 10,000 Data subjects: 1% of the Annual Gross Reveune of the preceding year or 2million naira, whichever is greater. ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "Nigeria Data Protection Regulation, 2019.",
    "Act URL": "https://ndpr.nitda.gov.ng/Content/Doc/NigeriaDataProtectionRegulation.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Reg.  3.1 (2)",
    "Compliance Name": "Data Access Request",
    "Compliance Description":
      "Inform data subject of the reason for not responding to a data access request and possibility of lodging complaint to supervisory authorities",
    "Task Frequency": "Within 1 month of receipt of request",
    Penalty:
      "Processing over 10, 000 Data Subjescts: 2% of the Annual Gross Revenue of the preceding year or 10million Naira which ever is greater;  Less than 10,000 Data subjects: 1% of the Annual Gross Reveune of the preceding year or 2million naira, whichever is greater. ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "Nigeria Data Protection Regulation, 2019.",
    "Act URL": "https://ndpr.nitda.gov.ng/Content/Doc/NigeriaDataProtectionRegulation.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Reg.  3.1 (7)",
    "Compliance Name": "Information to be provided to Data Subject",
    "Compliance Description":
      "Provide data subjects with the identity of the DPO, controller, the purpose of processing the data etc.",
    "Task Frequency": "Prior to data collection",
    Penalty:
      "Processing over 10, 000 Data Subjescts: 2% of the Annual Gross Revenue of the preceding year or 10million Naira which ever is greater;  Less than 10,000 Data subjects: 1% of the Annual Gross Reveune of the preceding year or 2million naira, whichever is greater. ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "Nigeria Data Protection Regulation, 2019.",
    "Act URL": "https://ndpr.nitda.gov.ng/Content/Doc/NigeriaDataProtectionRegulation.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Reg. 3.1 (13)",
    "Compliance Name": "Communicate rectification or erasure ",
    "Compliance Description":
      "Communicate any rectification or erasure of personal data to any recipient of the data",
    "Task Frequency": "",
    Penalty:
      "Processing over 10, 000 Data Subjescts: 2% of the Annual Gross Revenue of the preceding year or 10million Naira which ever is greater;  Less than 10,000 Data subjects: 1% of the Annual Gross Reveune of the preceding year or 2million naira, whichever is greater. ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "Nigeria Data Protection Regulation, 2019.",
    "Act URL": "https://ndpr.nitda.gov.ng/Content/Doc/NigeriaDataProtectionRegulation.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Reg. 4.1 (1)",
    "Compliance Name": "Publication of privacy policies ",
    "Compliance Description":
      "The company must make available to the public the company's data protection policies",
    "Task Frequency": "Within 3 months of issuance of this regulation",
    Penalty:
      "Processing over 10, 000 Data Subjescts: 2% of the Annual Gross Revenue of the preceding year or 10million Naira which ever is greater;  Less than 10,000 Data subjects: 1% of the Annual Gross Reveune of the preceding year or 2million naira, whichever is greater. ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "Nigeria Data Protection Regulation, 2019.",
    "Act URL": "https://ndpr.nitda.gov.ng/Content/Doc/NigeriaDataProtectionRegulation.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Reg. 4.1 (2) & (3)",
    "Compliance Name": "Appointment of DPO and capacity building for staff",
    "Compliance Description":
      "Appoint a data protection officer (DPO) and ensure continuous capacity building for the officer  and all members of staff",
    "Task Frequency": "At all times",
    Penalty:
      "Processing over 10, 000 Data Subjescts: 2% of the Annual Gross Revenue of the preceding year or 10million Naira which ever is greater;  Less than 10,000 Data subjects: 1% of the Annual Gross Reveune of the preceding year or 2million naira, whichever is greater. ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "Nigeria Data Protection Regulation, 2019.",
    "Act URL": "https://ndpr.nitda.gov.ng/Content/Doc/NigeriaDataProtectionRegulation.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Reg. 4.1 (5)",
    "Compliance Name": "Data Protection Audit",
    "Compliance Description":
      "Conduct a detailed audit of the company's privacy and data protection practices.",
    "Task Frequency": "Within 6 months of issuance of the regulation",
    Penalty:
      "Processing over 10, 000 Data Subjescts: 2% of the Annual Gross Revenue of the preceding year or 10million Naira which ever is greater;  Less than 10,000 Data subjects: 1% of the Annual Gross Reveune of the preceding year or 2million naira, whichever is greater. ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "Nigeria Data Protection Regulation, 2019.",
    "Act URL": "https://ndpr.nitda.gov.ng/Content/Doc/NigeriaDataProtectionRegulation.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Reg. 4.1 (6) & (7)",
    "Compliance Name": "Submission of NITDA Audit report to the Agency",
    "Compliance Description":
      "Submit a NITDA Audit report where the company processes data of up to 1000  data subject within 6 months or data of up to 2000 data subject in a period of 12 months",
    "Task Frequency": "Annual basis, not later than 15th March ",
    Penalty:
      "Processing over 10, 000 Data Subjescts: 2% of the Annual Gross Revenue of the preceding year or 10million Naira which ever is greater;  Less than 10,000 Data subjects: 1% of the Annual Gross Reveune of the preceding year or 2million naira, whichever is greater. ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "Nigeria Data Protection Regulation 2019: Implementation Framework 2020",
    "Act URL": "https://nitda.gov.ng/wp-content/uploads/2021/01/NDPR-Implementation-Framework.pdf",
    Regulator: "National Information Development Agency (NITDA)",
    Section: " Article 3.2(i)",
    "Compliance Name": "Compliance Checklist for Data Controllers and Data Administrators",
    "Compliance Description": "Conduct a data protection audit.",
    "Task Frequency": "Within 12 Months of incoporation and then on an annual basis.",
    Penalty:
      "Fine or adminstrative sanctions like suspension, public notice to warn the public to desist from patronizing or doing business with the affected party etc",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "Nigeria Data Protection Regulation 2019: Implementation Framework 2021",
    "Act URL": "https://nitda.gov.ng/wp-content/uploads/2021/01/NDPR-Implementation-Framework.pdf",
    Regulator: "National Information Development Agency (NITDA)",
    Section: "Article 3.2 (iii)",
    "Compliance Name": "Compliance Checklist for Data Controllers and Data Administrators",
    "Compliance Description":
      "Prepare and publish a private policy on every medium of personal data collection ",
    "Task Frequency": "Within 3 months of commencement of business",
    Penalty:
      "Fine or adminstrative sanctions like suspension, public notice to warn the public to desist from patronizing or doing business with the affected party etc",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "Nigeria Data Protection Regulation 2019: Implementation Framework 2022",
    "Act URL": "https://nitda.gov.ng/wp-content/uploads/2021/01/NDPR-Implementation-Framework.pdf",
    Regulator: "National Information Development Agency (NITDA)",
    Section: "Article 3.2 (iv-v)",
    "Compliance Name": "Compliance Checklist for Data Controllers and Data Administrators",
    "Compliance Description":
      "Publicize their private policy and design and maintain systems to be data protection compliant.",
    "Task Frequency": "At all times",
    Penalty:
      "Fine or adminstrative sanctions like suspension, public notice to warn the public to desist from patronizing or doing business with the affected party etc",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "Nigeria Data Protection Regulation 2019: Implementation Framework 2023",
    "Act URL": "https://nitda.gov.ng/wp-content/uploads/2021/01/NDPR-Implementation-Framework.pdf",
    Regulator: "National Information Development Agency (NITDA)",
    Section: "Article 3.2 (vi)",
    "Compliance Name": "Compliance Checklist for Data Controllers and Data Administrators",
    "Compliance Description":
      "Undertake continous building for members of staff, contractors, vendors, and relevant third parties.",
    "Task Frequency": "Periodically",
    Penalty:
      "Fine or adminstrative sanctions like suspension, public notice to warn the public to desist from patronizing or doing business with the affected party etc",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "NDPR Implementation Framework, 2020.",
    "Act URL": "https://nitda.gov.ng/wp-content/uploads/2021/01/NDPR-Implementation-Framework.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Article 3.2 (viii)",
    "Compliance Name": "Conduct a Data Protection Impact Assessment (DPIA) ",
    "Compliance Description":
      "Conduct a data protection impact assessment to identify possible areas where breaches may occur and devise a means of addressing those breaches where the company intends to embark on projects that would involve intense use of personal data",
    "Task Frequency": "Case by case basis",
    Penalty:
      "Fine or adminstrative sanctions like suspension, public notice to warn the public to desist from patronizing or doing business with the affected party etc",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "NDPR Implementation Framework, 2020.",
    "Act URL": "https://nitda.gov.ng/wp-content/uploads/2021/01/NDPR-Implementation-Framework.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Article 3.2 (ix) and 9.1",
    "Compliance Name": "Notification of data breach",
    "Compliance Description": "Notify NITDA of personal data breaches  ",
    "Task Frequency": "Within 72 hours of being aware of it",
    Penalty:
      "Fine or adminstrative sanctions like suspension, public notice to warn the public to desist from patronizing or doing business with the affected party etc",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "NDPR Implementation Framework, 2020.",
    "Act URL": "https://nitda.gov.ng/wp-content/uploads/2021/01/NDPR-Implementation-Framework.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Article 3.2 (x)",
    "Compliance Name": "Agreement with third party processor",
    "Compliance Description": "Update agreements with third party processors",
    "Task Frequency": "At all times",
    Penalty:
      "Fine or adminstrative sanctions like suspension, public notice to warn the public to desist from patronizing or doing business with the affected party etc",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "NDPR Implementation Framework, 2020.",
    "Act URL": "https://nitda.gov.ng/wp-content/uploads/2021/01/NDPR-Implementation-Framework.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Article 3.2 (xi)",
    "Compliance Name": "Data request",
    "Compliance Description": "Design system to make data requests and access seamless",
    "Task Frequency": "At all times",
    Penalty:
      "Fine or adminstrative sanctions like suspension, public notice to warn the public to desist from patronizing or doing business with the affected party etc",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "NDPR Implementation Framework, 2020.",
    "Act URL": "https://nitda.gov.ng/wp-content/uploads/2021/01/NDPR-Implementation-Framework.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Article 3.2 (xii)",
    "Compliance Name": "Update of personal data",
    "Compliance Description":
      "Design systems to enable Data Subjects to easily correct or update their Personal Data",
    "Task Frequency": "At all times",
    Penalty:
      "Fine or adminstrative sanctions like suspension, public notice to warn the public to desist from patronizing or doing business with the affected party etc",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "NDPR Implementation Framework, 2020.",
    "Act URL": "https://nitda.gov.ng/wp-content/uploads/2021/01/NDPR-Implementation-Framework.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Article 3.2 (xiii)",
    "Compliance Name": "Transfer of data by data subject",
    "Compliance Description":
      "Design system to enable Data Subjects to easily transfer data to another platform or person",
    "Task Frequency": "At all times",
    Penalty:
      "Fine or adminstrative sanctions like suspension, public notice to warn the public to desist from patronizing or doing business with the affected party etc",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "NDPR Implementation Framework, 2020.",
    "Act URL": "https://nitda.gov.ng/wp-content/uploads/2021/01/NDPR-Implementation-Framework.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Article 3.2 (xiv)",
    "Compliance Name": "Mandatory training of members of senior management and employee",
    "Compliance Description":
      "Train members of senior management and employees that collect and/or process Personal Data on Nigerian data protection laws and practices",
    "Task Frequency": "Within first 6 months and then bi-annual basis",
    Penalty:
      "Fine or adminstrative sanctions like suspension, public notice to warn the public to desist from patronizing or doing business with the affected party etc",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "NDPR Implementation Framework, 2020.",
    "Act URL": "https://nitda.gov.ng/wp-content/uploads/2021/01/NDPR-Implementation-Framework.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Article 3.2 (xv)",
    "Compliance Name": "Objection to processing of personal data",
    "Compliance Description":
      "Communicate to Data Subjects the process for objecting to the processing of their Personal Data",
    "Task Frequency": "At all times",
    Penalty:
      "Fine or adminstrative sanctions like suspension, public notice to warn the public to desist from patronizing or doing business with the affected party etc",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "NDPR Implementation Framework, 2020.",
    "Act URL": "https://nitda.gov.ng/wp-content/uploads/2021/01/NDPR-Implementation-Framework.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Article 3.2 (xvi)",
    "Compliance Name": "Automated decision",
    "Compliance Description":
      "Outline the procedure for informing Data Subject and for protecting their rights, where an automated decision is being made on their Personal Data.",
    "Task Frequency": "At all times",
    Penalty:
      "Fine or adminstrative sanctions like suspension, public notice to warn the public to desist from patronizing or doing business with the affected party etc",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "NDPR Implementation Framework, 2020.",
    "Act URL": "https://nitda.gov.ng/wp-content/uploads/2021/01/NDPR-Implementation-Framework.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Article 3.4.1 & 3.5",
    "Compliance Name": "Appointment of Data Protection Officer",
    "Compliance Description": "Appoint a dedicated DPO resident in Nigeria",
    "Task Frequency":
      "Within 6 months of commencing business or 6months of issuance of the framework",
    Penalty:
      "Fine or adminstrative sanctions like suspension, public notice to warn the public to desist from patronizing or doing business with the affected party etc",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "NDPR Implementation Framework, 2020.",
    "Act URL": "https://nitda.gov.ng/wp-content/uploads/2021/01/NDPR-Implementation-Framework.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Article 7.3",
    "Compliance Name":
      "Report of Binding Corporate rule (BCC) and Standard Contracting Clause (SCC)",
    "Compliance Description":
      "Provide BCR and SCC to be adopted by the company and report  to NITDA where the company seeks to transfer personal data to another entity within group of companies or affiliates company",
    "Task Frequency": "At all times",
    Penalty:
      "Fine or adminstrative sanctions like suspension, public notice to warn the public to desist from patronizing or doing business with the affected party etc",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "Nigeria Data Protection Regulation 2019: Implementation Framework 2020",
    "Act URL": "https://nitda.gov.ng/wp-content/uploads/2021/01/NDPR-Implementation-Framework.pdf",
    Regulator: "National Information Development Agency (NITDA)",
    Section: "Article 8.0",
    "Compliance Name": "Retention of Records",
    "Compliance Description":
      "Data controllers shall specify the duration of storage clearly in its terms of service or other binding document. Where the time for retention is not stated in the contract, the time stipulated in the act will suffice.",
    "Task Frequency":
      " Within 3 years after the last active use of a digital platform or 6 years after the last transaction in a contractual agreement or immediately upon request by the data subject.",
    Penalty:
      "Fine or adminstrative sanctions like suspension, public notice to warn the public to desist from patronizing or doing business with the affected party etc",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "Nigeria Data Protection Regulation 2019: Implementation Framework 2020",
    "Act URL": "https://nitda.gov.ng/wp-content/uploads/2021/01/NDPR-Implementation-Framework.pdf",
    Regulator: "National Information Development Agency (NITDA)",
    Section: "Article 10.1.4",
    "Compliance Name": "Administrative Sanction",
    "Compliance Description":
      "Where NITDA has acertained that a party is in breach, it may issue monetary fine.",
    "Task Frequency": "Whenever there is a breach",
    Penalty:
      "Fine or adminstrative sanctions like suspension, public notice to warn the public to desist from patronizing or doing business with the affected party etc",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "NDPR Implementation Framework, 2020.",
    "Act URL": "https://nitda.gov.ng/wp-content/uploads/2021/01/NDPR-Implementation-Framework.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Article 12.2",
    "Compliance Name": "Publication of list of Third Party Processor",
    "Compliance Description":
      "Publish a list of third parties with whom the Data Subject's Personal Data may be shared.",
    "Task Frequency": "At all times",
    Penalty:
      "Fine or adminstrative sanctions like suspension, public notice to warn the public to desist from patronizing or doing business with the affected party etc",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ":
      "African Union Convention on Cyber Security and Personal Data Protection (Malabo Convention) 2014.",
    "Act URL":
      "https://au.int/sites/default/files/treaties/29560-treaty-0048_-_african_union_convention_on_cyber_security_and_personal_data_protection_e.pdf",
    Regulator: "African Union Commission",
    Section: "Article 4.3",
    "Compliance Name": "Prohibition of online marketing without consent",
    "Compliance Description":
      "Not to send online marketing to recipient without obtaining consent ",
    "Task Frequency": "At all times",
    Penalty: "Criminal fines as stipulated by Member State ",
    Criticality: "Low",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ":
      "African Union Convention on Cyber Security and Personal Data Protection (Malabo Convention) 2014.",
    "Act URL":
      "https://au.int/sites/default/files/treaties/29560-treaty-0048_-_african_union_convention_on_cyber_security_and_personal_data_protection_e.pdf",
    Regulator: "African Union Commission",
    Section: "Article 4.5",
    "Compliance Name": "Opt-out message",
    "Compliance Description": "Not to send marketing messages without indicating a opt-out option",
    "Task Frequency": "At all times",
    Penalty: "Criminal fines as stipulated by Member State ",
    Criticality: "Low",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ":
      "African Union Convention on Cyber Security and Personal Data Protection (Malabo Convention) 2014.",
    "Act URL":
      "https://au.int/sites/default/files/treaties/29560-treaty-0048_-_african_union_convention_on_cyber_security_and_personal_data_protection_e.pdf",
    Regulator: "African Union Commission",
    Section: "Article 14.6 (b)",
    "Compliance Name": "Transfer of Personal Data to Non-Member State",
    "Compliance Description":
      "Not to transfer personal data to a non-member State of AU unless such a State ensures an adequate level of Protection of privacy",
    "Task Frequency": "At all times",
    Penalty: "Criminal fines as stipulated by Member State ",
    Criticality: "Low",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ":
      "African Union Convention on Cyber Security and Personal Data Protection (Malabo Convention) 2014.",
    "Act URL":
      "https://au.int/sites/default/files/treaties/29560-treaty-0048_-_african_union_convention_on_cyber_security_and_personal_data_protection_e.pdf",
    Regulator: "African Union Commission",
    Section: "Article 16",
    "Compliance Name": "Disclosure of information to Data subject",
    "Compliance Description":
      "Provide data subject with name of the company, purpose of processing period of storage,recipient to which data would be disclosed etc.",
    "Task Frequency": "At the point of data collection",
    Penalty: "Criminal fines as stipulated by Member State ",
    Criticality: "Low",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ":
      "African Union Convention on Cyber Security and Personal Data Protection (Malabo Convention) 2014.",
    "Act URL":
      "https://au.int/sites/default/files/treaties/29560-treaty-0048_-_african_union_convention_on_cyber_security_and_personal_data_protection_e.pdf",
    Regulator: "African Union Commission",
    Section: "Article 20",
    "Compliance Name": "Confidentiality obligation",
    "Compliance Description":
      "Process personal data only on the authority of a data controller and only on instructions of the data controller.",
    "Task Frequency": "At all times",
    Penalty: "Criminal fines as stipulated by Member State",
    Criticality: "Low",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ":
      "African Union Convention on Cyber Security and Personal Data Protection (Malabo Convention) 2014.",
    "Act URL":
      "https://au.int/sites/default/files/treaties/29560-treaty-0048_-_african_union_convention_on_cyber_security_and_personal_data_protection_e.pdf",
    Regulator: "African Union Commission",
    Section: "Article 21",
    "Compliance Name": "Data security obligation",
    "Compliance Description": "Keep data collected secure ",
    "Task Frequency": "At all times",
    Penalty: "Criminal fines as stipulated by Member State ",
    Criticality: "Low",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ":
      "African Union Convention on Cyber Security and Personal Data Protection (Malabo Convention) 2014.",
    "Act URL":
      "https://au.int/sites/default/files/treaties/29560-treaty-0048_-_african_union_convention_on_cyber_security_and_personal_data_protection_e.pdf",
    Regulator: "African Union Commission",
    Section: "Article 22",
    "Compliance Name": "Retention Policy",
    "Compliance Description": "Retain data for necessary purposes only",
    "Task Frequency": "At all times",
    Penalty: "Criminal fines as stipulated by Member State (see Article 31 (c))",
    Criticality: "Low",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Regulation (EU) 2016/679",
    "Legislation Name ": "European Union General Data Protection Regulation",
    "Act URL": "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016R0679",
    Regulator: "European Commission",
    Section: "Article 13 & 14",
    "Compliance Name": "Provision of Necessary Information to Data Subject",
    "Compliance Description":
      "Provide data subject with the following information whether personal data is obtained directly from the data subject or not: name of the company, contact of DPO, purpose of data collection, transfer to foreign country, retention period, recipient of data, right to request rectification or erasure. ",
    "Task Frequency":
      "At the time of obtaining the data or within one month of request from data subject",
    Penalty: "Adminstrative fine or as stipulated by Member States",
    Criticality: "Medium",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Regulation (EU) 2016/679",
    "Legislation Name ": "European Union General Data Protection Regulation",
    "Act URL": "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016R0680",
    Regulator: "European Commission",
    Section: "Article 24 & 25",
    "Compliance Name": "Implement all Measures to ensure compliance",
    "Compliance Description":
      "Implement appropriate technical and organisational measures e.g pseudonymisation and data minimisation. Implement a data protection policy.",
    "Task Frequency": "Upon determing the means of processing and during processing",
    Penalty: "Adminstrative fine or as stipulated by Member States",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Regulation (EU) 2016/679",
    "Legislation Name ": "European Union General Data Protection Regulation",
    "Act URL": "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016R0681",
    Regulator: "European Commission",
    Section: "Article 28",
    "Compliance Name": "Use of Processor",
    "Compliance Description":
      "Use only data processors who provide sufficient guarantee to implement appropriate technical and organisational measures to ensure safety of data. Data processing must be governed by a contract.  ",
    "Task Frequency": "At all times",
    Penalty: "Adminstrative fine or as stipulated by Member States",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Regulation (EU) 2016/679",
    "Legislation Name ": "European Union General Data Protection Regulation",
    "Act URL": "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016R0682",
    Regulator: "European Commission",
    Section: "Article 29",
    "Compliance Name": "Processing according to the instruction of controller",
    "Compliance Description":
      "Not to process data except on instruction from the controller unless required by state laws",
    "Task Frequency": "At all times",
    Penalty: "Adminstrative fine or as stipulated by Member States",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Regulation (EU) 2016/679",
    "Legislation Name ": "European Union General Data Protection Regulation",
    "Act URL": "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016R0682",
    Regulator: "European Commission",
    Section: "Article 30",
    "Compliance Name": "Maintain record of processing activities ",
    "Compliance Description":
      "Maintain a record of processing activities under the company's responsibility",
    "Task Frequency": "",
    Penalty: "Adminstrative fine or as stipulated by Member States",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Regulation (EU) 2016/679",
    "Legislation Name ": "European Union General Data Protection Regulation",
    "Act URL": "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016R0683",
    Regulator: "European Commission",
    Section: "Article 33",
    "Compliance Name":
      "Notification and Documentation of Personal Data Breach to supervisory authority",
    "Compliance Description":
      "Notify supervisory authority of any personal data breaches, document and provide facts relating to the breach and remedial actions taken ",
    "Task Frequency": "Within 72 Hours of being aware of the breach ",
    Penalty: "Adminstrative fine or as stipulated by Member States",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Regulation (EU) 2016/679",
    "Legislation Name ": "European Union General Data Protection Regulation",
    "Act URL": "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016R0684",
    Regulator: "European Commission",
    Section: "Article 34",
    "Compliance Name": "Communication of Personal data breach to Data Subject",
    "Compliance Description":
      "Communicate any breach likely to result in a high risk to rights of data subject in a clear and plain language.",
    "Task Frequency": "Without Undue Delay",
    Penalty: "Adminstrative fine or as stipulated by Member States",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Regulation (EU) 2016/679",
    "Legislation Name ": "European Union General Data Protection Regulation",
    "Act URL": "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016R0685",
    Regulator: "European Commission",
    Section: "Article 35 & 36",
    "Compliance Name": "Duty to carry out DPIA and consult supervisory authority",
    "Compliance Description":
      "Conduct a data impact assessment and consult supervisory authority where processing of personal data is subject to high risk ",
    "Task Frequency": "Prior to the Processing likely to cause high risk",
    Penalty: "Adminstrative fine or as stipulated by Member States",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Regulation (EU) 2016/679",
    "Legislation Name ": "European Union General Data Protection Regulation",
    "Act URL": "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016R0686",
    Regulator: "European Commission",
    Section: "Article 37",
    "Compliance Name": "Duty to designate DPO",
    "Compliance Description": "Designate a Data Protection Officer",
    "Task Frequency": "At all times",
    Penalty: "Adminstrative fine or as stipulated by Member States",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ":
      "OECD Revised Guidelines on the Protection of Privacy and Transborder Flows of Personal Data, 2013.",
    "Act URL": "https://www.oecd.org/sti/ieconomy/oecd_privacy_framework.pdf",
    Regulator: "OECD Council",
    Section: "section 15 (a)",
    "Compliance Name": "Privacy management programme",
    "Compliance Description": "Have in place a privacy management programme",
    "Task Frequency": "All the time",
    Penalty: "Nil",
    Criticality: "Low",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ":
      "OECD Revised Guidelines on the Protection of Privacy and Transborder Flows of Personal Data, 2013.",
    "Act URL": "https://www.oecd.org/sti/ieconomy/oecd_privacy_framework.pdf",
    Regulator: "OECD Council",
    Section: "section 15 ©",
    "Compliance Name": "Notification of privacy breach",
    "Compliance Description":
      "Must provide notice to privacy enforcement authorities where there is sgnificant breach affecting personal data",
    "Task Frequency": "All the time",
    Penalty: "Nil",
    Criticality: "Low",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "N/A",
    "Legislation Name ": "National Information Technology Development Agency Act, 2007.",
    "Act URL": "https://nitda.gov.ng/wp-content/uploads/2020/11/NITDA-ACT-2007-2019-Edition1.pdf",
    Regulator: "National Information Technology Development Agency",
    Section: "Section 17(4)",
    "Compliance Name": "Compliance with guidelines and Standards",
    "Compliance Description":
      "Must follow the guidelines and standards precribed by the agency in discharge of any duty impose by the Act",
    "Task Frequency": "All the time",
    Penalty: "fine or imprisonment or both upon conviction",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
];

export { customerDevelopment, corpoateAffairs, itComplaince };
