const customerDevelopment = [
  {
    "Act No": "Standards Organization of Nigeria Act",
    "Legislation Name ": "",
    "Act URL": "",
    Regulator: "",
    Section: "",
    "Compliance Name": "",
    "Compliance Description": "",
    "Task Frequency": "",
    Penalty: "",
    Criticality: "",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Cap. 59 LFN 2004",
    "Legislation Name ": "Standards Organization of Nigeria Act",
    "Act URL": "https://lawsofnigeria.placng.org/laws/S9.pdf",
    Regulator: "Standard Council of Nigeria",
    Section: "Section 16",
    "Compliance Name": "Duty to compliance with established standards",
    "Compliance Description":
      "The Company is  expected to comply with the manufacture industrial standard that will from time to time be set by the Minister. ",
    "Task Frequency": "At all times",
    Penalty: "Conviction with fine and or imprisonment or both.",
    Criticality: "High",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Trade Mark Act",
    "Legislation Name ": "",
    "Act URL": "",
    Regulator: "",
    Section: "",
    "Compliance Name": "",
    "Compliance Description": "",
    "Task Frequency": "",
    Penalty: "",
    Criticality: "",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Cap T13 LFN 2004",
    "Legislation Name ": "Trade Mark Act",
    "Act URL": "https://nigeria.tradeportal.org/media/Trade%20Mark%20Act.pdf",
    Regulator: "Nigerian Trademarks Registry",
    Section: "Section 11",
    "Compliance Name": "Duty not to register deceptive, confusing and scandalous trade marks.",
    "Compliance Description": " Deceptive or scandalous marks are not registrable",
    "Task Frequency": "Atll all times",
    Penalty: "Not stated",
    Criticality: "Low",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No":
      "Counterfeit and Fake Drugs and Unwholesome Processed Foods (Miscellaneous Provisions) Act",
    "Legislation Name ": "",
    "Act URL": "",
    Regulator: "",
    Section: "",
    "Compliance Name": "",
    "Compliance Description": "",
    "Task Frequency": "",
    Penalty: "",
    Criticality: "",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Cap. C34 LFN 2004",
    "Legislation Name ":
      "Counterfeit and Fake Drugs and Unwholesome Processed Foods (Miscellaneous Provisions) Act",
    "Act URL":
      "https://www.nafdac.gov.ng/wp-content/uploads/Files/Resources/Regulations/NAFDAC_Acts/COUNTERFEIT-AND-FAKE-DRUGS-AND-UNWHOLESOME-PROCESSED-FOODS-Cap.-C.34.pdf",
    Regulator: "Federal Task Force",
    Section: "Section 1",
    "Compliance Name":
      "Duty not to sell counterfeit and fake drugs and unwholesome processed foods",
    "Compliance Description":
      "The Company shall not  produce, import, manufacture, sell, distribute or be in possession of; or sell or display for the purpose of sale; or aid or abet any person to produce, import, manufacture, sell, distribute or display for the purpose of sale, any counterfeit, adulterated, banned or fake, substandard or expired drug or unwholesome processed food, in any form whatsoever.",
    "Task Frequency": "At all times",
    Penalty: "Conviction with fine and or imprisonment for company and officers/directors",
    Criticality: "High",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Federal Competition and Consumer Protection Act (FCCPA) 2018",
    "Legislation Name ": "",
    "Act URL": "",
    Regulator: "",
    Section: "",
    "Compliance Name": "",
    "Compliance Description": "",
    "Task Frequency": "",
    Penalty: "",
    Criticality: "",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "2018",
    "Legislation Name ": "Federal Competition and Consumer Protection Act (FCCPA)",
    "Act URL": "https://www.fccpc.gov.ng/uploads/FCCPA.pdf",
    Regulator: "Federal Competiton and Consumer Protection Commission",
    Section: "Section 114",
    "Compliance Name": "Duty to publis information in plain and understandable language",
    "Compliance Description":
      "Producer should produce information in plain and understandable language.",
    "Task Frequency": "At all times",
    Penalty: "Conviction with fine for company and officers/directors",
    Criticality: "High",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "2018",
    "Legislation Name ": "Federal Competition and Consumer Protection Act (FCCPA)",
    "Act URL": "https://www.fccpc.gov.ng/uploads/FCCPA.pdf",
    Regulator: "Federal Competiton and Consumer Protection Commission",
    Section: "Section 115",
    "Compliance Name": "Duty to disclose  of price of goods and services.",
    "Compliance Description":
      "The Company shall not display any goods or services for sale without adequately displaying to the consumer a price of those goods or services.",
    "Task Frequency": "At all times",
    Penalty: "Conviction with fine for company and officers/directors",
    Criticality: "High",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "2018",
    "Legislation Name ": "Federal Competition and Consumer Protection Act (FCCPA)",
    "Act URL": "https://www.fccpc.gov.ng/uploads/FCCPA.pdf",
    Regulator: "Federal Competiton and Consumer Protection Commission",
    Section: "Section 116 (3)",
    "Compliance Name": "Duty not to sell goods with misleading or altered trade descriptions.",
    "Compliance Description":
      " The company shall not sell to customers goods with misleading or altered trade descriptions",
    "Task Frequency": "At all times",
    Penalty: "Conviction with fine for company and officers/directors",
    Criticality: "High",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "2018",
    "Legislation Name ": "Federal Competition and Consumer Protection Act (FCCPA)",
    "Act URL": "https://www.fccpc.gov.ng/uploads/FCCPA.pdf",
    Regulator: "Federal Competiton and Consumer Protection Commission",
    Section: "Section 117",
    "Compliance Name":
      "Duty to disclose when goods have been  reconditioned or are second-hand goods.",
    "Compliance Description":
      " The Company must inform customers if the goods for sale have been recnditioned or are second hand goods",
    "Task Frequency": "At all times",
    Penalty: "Conviction with fine for company and officers/directors",
    Criticality: "High",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "2018",
    "Legislation Name ": "Federal Competition and Consumer Protection Act (FCCPA)",
    "Act URL": "https://www.fccpc.gov.ng/uploads/FCCPA.pdf",
    Regulator: "Federal Competiton and Consumer Protection Commission",
    Section: "Section 123(1)",
    "Compliance Name": "Duty not to misrepresent facts to consumers when marketing goods.",
    "Compliance Description":
      "The Company shall not to make any representation that is likely to imply false or incorrect representation concerning goods and services  ",
    "Task Frequency": "At all times",
    Penalty: "Conviction with fine for company and officers/directors",
    Criticality: "High",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "2018",
    "Legislation Name ": "Federal Competition and Consumer Protection Act (FCCPA)",
    "Act URL": "https://www.fccpc.gov.ng/uploads/FCCPA.pdf",
    Regulator: "Federal Competiton and Consumer Protection Commission",
    Section: "Section 127(1)",
    "Compliance Name": "Duty not sell goods at unfair, unreasonable, or unjust contract terms.",
    "Compliance Description":
      "The company shall not offer to supply, supply or enter into an agreement to supply any goods or services at a price that is manifestly unfair, unreasonable or unjust or on terms that are unfair, unreasonable or unjust.",
    "Task Frequency": "At all times",
    Penalty: "Conviction with fine for company and officers/directors",
    Criticality: "High",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "2018",
    "Legislation Name ": "Federal Competition and Consumer Protection Act (FCCPA)",
    "Act URL": "https://www.fccpc.gov.ng/uploads/FCCPA.pdf",
    Regulator: "Federal Competiton and Consumer Protection Commission",
    Section: "Section 134",
    "Compliance Name": "Duty to label goods properly",
    "Compliance Description":
      "The Company shall label or describe the goods in a manner that will be easily traceable to the manufacturer, importer, or distributor",
    "Task Frequency": "At all times",
    Penalty: "Conviction with fine for company and officers/directors",
    Criticality: "High",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "2018",
    "Legislation Name ": "Federal Competition and Consumer Protection Act (FCCPA)",
    "Act URL": "https://www.fccpc.gov.ng/uploads/FCCPA.pdf",
    Regulator: "Federal Competiton and Consumer Protection Commission",
    Section: "Section 135",
    "Compliance Name": "Duty to withdraw hazardous goods from the market.",
    "Compliance Description":
      "Upon becoming aware of any unforeseen hazard arising from the use of goods already placed on the market, the company  such goods shall notify the general public immediately of such risk or danger and cause such goods to be withdrawn from the market",
    "Task Frequency": "Upon becoming aware",
    Penalty: "Conviction with fine for company and officers/directors",
    Criticality: "High",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "NAFDAC Cosmetic Products (Prohibition of bleaching agents, etc) Regulations ",
    "Legislation Name ": "",
    "Act URL": "",
    Regulator: "",
    Section: "",
    "Compliance Name": "",
    "Compliance Description": "",
    "Task Frequency": "",
    Penalty: "",
    Criticality: "",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Cap. N1 LFN 2004",
    "Legislation Name ":
      "NAFDAC Cosmetic Products (Prohibition of bleaching agents, etc) Regulations ",
    "Act URL":
      "https://www.nafdac.gov.ng/wp-content/uploads/Files/Resources/Regulations/NAFDAC_Acts/NAFDAC-ACT-Cap-N.-1-LFN-2004.pdf",
    Regulator: "NAFDAC",
    Section: "Regulation 1",
    "Compliance Name": "Duty not to sell adulterated cosmetic products",
    "Compliance Description":
      "The Company shall not engage in the sale of adulterated, injurious or cosmetic  products with bleaching agents.",
    "Task Frequency": "At all times",
    Penalty: "Conviction with fine and or imprisonment",
    Criticality: "High",
    "Significant Judicial Intervention": null,
    YES: null,
    NDD: null,
    NO: null,
  },
];

const corpoateAffairs = [
  {
    "Act No": "Cybercrimes (Prohibition and Prevention) Act, 2015",
    "Legislation Name ": "",
    "Act URL": "",
    Regulator: "",
    Section: "",
    "Compliance Name": "",
    "Compliance Description": "",
    "Task Frequency": "",
    Penalty: "",
    Criticality: "",
    "Significant Judicial Intervention": "",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2015,
    "Legislation Name ": " Cybercrimes (Prohibition, Prevention, Etc) Act, 2015 ",
    "Act URL":
      "https://www.cert.gov.ng/ngcert/resources/CyberCrime__Prohibition_Prevention_etc__Act__2015.pdf",
    Regulator: "Office of the National Security Adviser (NSA)",
    Section: "Section 17 (1) (a)",
    "Compliance Name": "Electronic signature",
    "Compliance Description":
      "Do not with the intent to defraud and or misrepresent, forge through electronic devices another person or company’s signature ",
    "Task Frequency": "All the time",
    Penalty: "Conviction with fine and/ or imprisonment.",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2015,
    "Legislation Name ": " Cybercrimes (Prohibition, Prevention, Etc) Act, 2015 ",
    "Act URL":
      "https://www.cert.gov.ng/ngcert/resources/CyberCrime__Prohibition_Prevention_etc__Act__2015.pdf",
    Regulator: "Office of the National Security Adviser (NSA)",
    Section: "Section 21 (1) and (3) ",
    "Compliance Name": "Reporting of Cyber Threats",
    "Compliance Description":
      "Inform the National Computer Emergency Response Team (CERT) Coordination Center of any attacks, intrusions and other disruptions liable to hinder the functioning of another computer system or network.",
    "Task Frequency": "Within 7 days of occurrence ",
    Penalty: "Fine and denial of internet services",
    Criticality: "Medium",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2015,
    "Legislation Name ": " Cybercrimes (Prohibition, Prevention, Etc) Act, 2015 ",
    "Act URL":
      "https://www.cert.gov.ng/ngcert/resources/CyberCrime__Prohibition_Prevention_etc__Act__2015.pdf",
    Regulator: "Office of the National Security Adviser (NSA)",
    Section: "Section 25 (1)",
    "Compliance Name": "Cybersquatting ",
    "Compliance Description":
      "Do not intentionally take or make use of any brand identity or trademark belonging to an individual, company or the government, on the internet or any other computer network, without authority or right, for the purpose of interfering with their use.",
    "Task Frequency": "All the time",
    Penalty: "Conviction with fine and/ or imprisonment.",
    Criticality: "Medium",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": "Federal Competition and Consumer Protection Act 2018",
    "Legislation Name ": "",
    "Act URL": "",
    Regulator: "",
    Section: "",
    "Compliance Name": "",
    "Compliance Description": "",
    "Task Frequency": "",
    Penalty: "",
    Criticality: "",
    "Significant Judicial Intervention": "",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 28(5) & 31",
    "Compliance Name": "Duty to provide reasonable facility to authorised officer  ",
    "Compliance Description":
      "Provide reasonable facilities and assistance to an authorised officer in executing a warrant issued under the Act",
    "Task Frequency": "All the time",
    Penalty: "Fine or imprisonment",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 33 (3)",
    "Compliance Name": "Summons to attend and give evidence or produce documents",
    "Compliance Description":
      "Appear before the commission in compliance with a summons or produce required documents",
    "Task Frequency": "All the time",
    Penalty: "Fine or imprisonment",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 36",
    "Compliance Name": "Duty to preserve records",
    "Compliance Description":
      "Do not destroy records with the intent to mislead the commission or impede any investigation or inquiry",
    "Task Frequency": "All the time",
    Penalty: "Fine or imprisonment",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 59",
    "Compliance Name": "Restrictive agreements",
    "Compliance Description":
      "Do not draft agreements that seeks to prevent, restrict or distort competition in any market, except authorised by the commission",
    "Task Frequency": "All the time",
    Penalty: "On conviction, fine or 10% of it turnover and corporate liability",
    Criticality: "Low",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 61 - 63",
    "Compliance Name": "Avoid collision arrangements/agreements ",
    "Compliance Description":
      "Do not enter any collision arrangement with any undertaking that seeks to distort demand and supply or free market compeition",
    "Task Frequency": "All the time",
    Penalty: "On conviction, fine or 10% of it turnover and corporate liability",
    Criticality: "Low",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 65",
    "Compliance Name": "Prohibition of minimum resale price maintenance.",
    "Compliance Description":
      "Do not enter into any agreement that seeks to withhold supplies of any goods or services from a dealer seeking to obtain them for resale on the ground that the dealer has sold goods or services at a price below the resale price or has supplied them to a third party who had done so.",
    "Task Frequency": "All the time",
    Penalty: "On conviction, fine or 10% of it turnover and corporate liability",
    Criticality: "Low",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 78(b) & 80",
    "Compliance Name": "Duty to furnish information ",
    "Compliance Description":
      "When the commission is conducting any monopoly investigation, the company  is expected to furnish the commission with such information as the commission may consider necessary for the purpose of conducting such investigation.",
    "Task Frequency": "Upon receiving notice in writing from the commission",
    Penalty: "Fine",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 95(3)",
    "Compliance Name": " Small merger notification",
    "Compliance Description":
      "The commission may require the parties to a small merger to notify it of the merger if the merger substantially prevent or lessen competiton",
    "Task Frequency": "Within six month of the merger",
    Penalty: "Nil",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 96(1) (4)",
    "Compliance Name": "Notification of large merger ",
    "Compliance Description":
      "Notify the commission of a large merger and do not implement it unless it is approved by the commision   ",
    "Task Frequency": "All the time",
    Penalty: "Action taken void",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 108",
    "Compliance Name": "Conspiracy to restrain trade",
    "Compliance Description":
      "Do not conspire with another business to limit the faciulities for transporting, producing, manufacturing, storing, and dealing in goods and services",
    "Task Frequency": "All the time",
    Penalty: "Fine max. of 10% of turnover and corporate liability ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 110",
    "Compliance Name": "Obstruction of investigation of inquiry",
    "Compliance Description": "Do not obstruct investigation or inquiry by the Commission.",
    "Task Frequency": "All the time",
    Penalty: "Fine max. of 10% of turnover and corporate liability ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 112",
    "Compliance Name": "Giving of false or misleading information",
    "Compliance Description":
      "Do not give the Commission or an authorized officer of the commission false or misleading information.",
    "Task Frequency": "All the time",
    Penalty: "Fine max. of 10% of turnover and corporate liability ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 114(1)",
    "Compliance Name": "Right of Information in a plain language",
    "Compliance Description":
      " All information notice or document meant to be displayed to consumer must be done in a plain language.",
    "Task Frequency": "All the time",
    Penalty: "Nil",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 115(1)",
    "Compliance Name": "Section Disclosure of Price of goods or service",
    "Compliance Description":
      "Do not display any goods or services for sale without adequately displaying to the consumer a price of those goods or services.",
    "Task Frequency": "All the time",
    Penalty: "Nil",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2018",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 116",
    "Compliance Name": "A trade description of misleading goods",
    "Compliance Description":
      "Trade description or labelling is required for goods that are likely to mislead consumers as to any matter implied or expressed in that trade description",
    "Task Frequency": "All the time",
    Penalty: "Nil",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2020",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 118",
    "Compliance Name": " Duty to provide sales record to Consumer",
    "Compliance Description":
      "Provide a written record of each transaction to any consumer to whom goods or services are sold or rendered to unless where it is impracticable ",
    "Task Frequency": "All the time",
    Penalty: "Nil",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2020",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 123",
    "Compliance Name": "General standards for the marketing of goods and services.",
    "Compliance Description":
      "Do not to make any representation that is likely to imply false or incorrect representation concerning the company's goods and services  ",
    "Task Frequency": "All the time",
    Penalty: "Nil",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2021",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 125",
    "Compliance Name": "Consumer's rights",
    "Compliance Description":
      "Do not give false, misleading or deceptive representations concerning a material fact to a consumer or prospective consumer or fails to correct an apparent misrepresentation.",
    "Task Frequency": "All the time",
    Penalty: "Exposure to civil laibility",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2021",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 126",
    "Compliance Name": "Representation and publication testimonials",
    "Compliance Description":
      "Do not make representation to the public that a test as to performance, efficacy or length of life of the goods or service has been made by any person or publish a testimonial to that effect unless as a stated in the Act ",
    "Task Frequency": "All the time",
    Penalty: "Nil",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2022",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 127",
    "Compliance Name": "Duty not to make Unfair and unreasonable contract terms ",
    "Compliance Description":
      "Do not offer or enter into an agreement to supply any goods and services that is manifestly unfair and unreasonable or unjust",
    "Task Frequency": "All the time",
    Penalty: "Nil",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2023",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 128",
    "Compliance Name": "Notice required to be provided to consumer in certain condition",
    "Compliance Description":
      "Any notice to consumer or potential consumer which purport to limit, impose or constitute a risk or liability on the consumer or any person shall be drawn to the attention of the consumer in a conspicous manner ",
    "Task Frequency": "All the time",
    Penalty: "Nil",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2023",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 129",
    "Compliance Name": "Consumer's rights",
    "Compliance Description":
      "Do not make any transaction or agreement seeking to defeat the purposes and policy of this Act, mislead or deceive the consumer, or subject a consumer to fraudulent conduct.",
    "Task Frequency": "All the time",
    Penalty: "Nil",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2023",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 134",
    "Compliance Name": "Duty to label goods properly",
    "Compliance Description":
      "Label or describe goods in a manner that will be easily traceable to the company",
    "Task Frequency": "All the time",
    Penalty: "Fine max. of 10% of turnover and corporate liability ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
  {
    "Act No": 2018,
    "Legislation Name ": "Federal Competition and Consumer Protection Act 2023",
    "Act URL": "FCCPA.pdf (fccpc.gov.ng)",
    Regulator: "Federal Competition and Consumer Protection Commission ",
    Section: "Section 135",
    "Compliance Name": "Duty to withdraw hazardous goods from the market.",
    "Compliance Description":
      "Notify the general public immediately of any unforeseen hazard arising from the use of goods already placed on the market, and cause such goods to be withdrawn from the market.",
    "Task Frequency": "Upon becoming aware",
    Penalty: "Fine max. of 10% of turnover and corporate liability ",
    Criticality: "High",
    "Significant Judicial Intervention": "NSC",
    YES: null,
    NDD: null,
    NO: null,
  },
];

export { customerDevelopment, corpoateAffairs };
